steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/test1-305123/docker-shutdown/python-shutdown', '.' ]

images:
  - 'us-central1-docker.pkg.dev/test1-305123/docker-shutdown/python-shutdown'